Task: Python script to crawl a cricket website
M-Shan/tech-crunchers pull request #11
Opened 2020-09-24 07:28 UTC by Raspberry-beans

This new python file grabs the data from the cricket website.
	All the links of results of matches have been saved in separate list.

Relates: 7

2020-09-25 17:06 UTC, Raspberry-beans commented
@M-Shan kindly update

2020-10-02 17:31 UTC, M-Shan commented on projects/news_feed/PSL_Matches.py
> +#and then stores the links of results of all matches in a list called All_Matches_Links
write proper script header.
e.g.

```
"""
    Script for ....

    :file: <filename.py>
    :platform: Windows, Linux
    :synopsis:
       Script to handle ...

    :author:
        - your name and email
"""
```

2020-10-02 17:31 UTC, M-Shan commented on projects/news_feed/PSL_Matches.py
> +from bs4 import BeautifulSoup
is `bs4` and `panda` added in `conf/requirements.txt` file?

2020-10-02 17:31 UTC, M-Shan commented on projects/news_feed/PSL_Matches.py
> +#This code grabs the data from the suggested website
change file name to `psl_matches.py`

2020-10-02 17:31 UTC, M-Shan commented on projects/news_feed/PSL_Matches.py
> +url = "https://www.espncricinfo.com/scores/series/8679/season/2020/pakistan-super-league?view=results"
you can save variables in a separate file

2020-10-02 17:31 UTC, M-Shan commented
> @M-Shan kindly update

@faheem-rehman review is done.
if something is un-clear you can contact.

2020-10-04 19:22 UTC, Raspberry-beans commented
@M-Shan kindly guide about how to save variables in separate file. Thanks!

2020-10-11 08:32 UTC, M-Shan commented
> @M-Shan kindly guide about how to save variables in separate file. Thanks!

you can do it as done in shared 2 scripts.

please change the script extension from `.txt` to `.py` and then try.
github doesn't allow `.py` file format uploading in reviews :(

[main.txt](https://github.com/M-Shan/TechCrunch/files/5360779/main.txt)
[utils.txt](https://github.com/M-Shan/TechCrunch/files/5360780/utils.txt)

2020-10-13 12:25 UTC, M-Shan commented
> > @M-Shan kindly guide about how to save variables in separate file. Thanks!
> 
> you can do it as done in shared 2 scripts.
> 
> please change the script extension from `.txt` to `.py` and then try.
> github doesn't allow `.py` file format uploading in reviews :(
> 
> [main.txt](https://github.com/M-Shan/TechCrunch/files/5360779/main.txt)
> [utils.txt](https://github.com/M-Shan/TechCrunch/files/5360780/utils.txt)

@Raspberry-beans any update?

2020-10-13 12:27 UTC, Raspberry-beans commented
Working on it 😌

2020-10-13 19:29 UTC, M-Shan requested changes
delete `projects/news_feed/__pycache__/utilities.cpython-37.pyc` 
add `__pycache__` in `.gitignore` file

2020-10-13 19:29 UTC, M-Shan commented on projects/news_feed/PSL_Matches.py
> +"""
rename this file as `psl_matches.py`

2020-10-13 19:29 UTC, M-Shan commented on conf/requirements.txt
> +Pnada
**Pnada** --> **Panda**

2020-10-15 08:43 UTC, M-Shan requested changes

2020-10-15 08:43 UTC, M-Shan commented on .gitignore
> +*.pyc
instead of this you can add `__pycache__` which will ignore all python compiled files

2020-10-15 08:43 UTC, M-Shan commented on conf/requirements.txt
> +Panda
apologies i mentioned it wrong 

this module name is `pandas`

2020-10-15 17:05 UTC, M-Shan approved these changes
Good job

2020-10-15 17:05 UTC, merged