Task: Create folder for project in Repository
M-Shan/tech-crunchers pull request #5
Opened 2020-08-30 17:14 UTC by Raspberry-beans

-Created project folder
 	-Created README.md file for project folder
 	-Created new project folder namde "news_feed"
 	-Created README.md file for new_feed project

 Relates: 4

2020-08-30 20:22 UTC, M-Shan requested changes
thanks for your first commit on the project 👍 
following are my comments:

- in **README.md** files write the folder purpose e.g. in project **README.md** file write that this folder will contain different projects code scripts, resources, artifacts etc.

in order to understand how to write markdown files (.md) read [this](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax).

in order to see how your markdown file will look like you can use [this ](https://markdownlivepreview.com/) website.

2020-08-30 20:24 UTC, M-Shan commented
in order to change your GitHub theme to dark mode then search for **GitHub Dark Theme
** at [Chrome Web Store](https://chrome.google.com/webstore/category/extensions).

2020-09-04 19:16 UTC, Raspberry-beans commented
> thanks for your first commit on the project 👍
> following are my comments:
> 
> * in **README.md** files write the folder purpose e.g. in project **README.md** file write that this folder will contain different projects code scripts, resources, artifacts etc.
> 
> in order to understand how to write markdown files (.md) read [this](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax).
> 
> in order to see how your markdown file will look like you can use [this ](https://markdownlivepreview.com/) website.

2020-09-04 19:26 UTC, Raspberry-beans commented
@M-Shan I have addressed the required changes in markdown files. Some of the syntax does not appear as it should be. Kindly help me to clear this issue!

2020-09-05 09:04 UTC, M-Shan commented
> @M-Shan I have addressed the required changes in markdown files. Some of the syntax does not appear as it should be. Kindly help me to clear this issue!

ok.
i see what's wrong --> you need to add a space after `#` for headings.
and for heading links there shall be no space after `]` --> an example is as follow: 
`[M-Shan TechCrunch projects](https://github.com/M-Shan/TechCrunch/projects)`

2020-09-05 09:06 UTC, M-Shan requested changes

2020-09-05 09:06 UTC, M-Shan commented on projects/README.md
> +##Contents available in projects folder
add space after `##`

2020-09-05 09:06 UTC, M-Shan commented on projects/news_feed/README.md
> +#Sports News Feed
add space after `#`

2020-09-05 09:06 UTC, M-Shan commented on projects/news_feed/README.md
> +##The purpose of this project is to inform its users about everydays sports events and news using a specially designed GUI (Graphical User Interface) system.
add space after `##`

2020-09-05 09:06 UTC, M-Shan commented on projects/news_feed/README.md
> +###Further advancement and code scritps will be shared soon
add space after `###`

2020-09-05 09:06 UTC, M-Shan commented on projects/news_feed/README.md
> +You can check the status of project by clicking on [M-Shan TechCrunch projects] (https://github.com/M-Shan/TechCrunch/projects)
remove space --> `unch projects](https`

2020-09-05 18:40 UTC, Raspberry-beans commented
@M-Shan All the issues related to README files have been resolved.
However, today I have noticed that my commits are mentioned with my old github ID faheem-rehman not Raspberry-beans
Can you find out where the actual problem is?
Thanks!

2020-09-06 10:10 UTC, M-Shan commented
> oticed that

im not sure how to address this issue.
if your account is not used then delete that one.

and after commit you can see wht's the name in commit message via `git log `

2020-09-06 10:10 UTC, M-Shan approved these changes
good work 👍

2020-09-06 10:11 UTC, merged